services:
  app:
    build:
      context: src
      dockerfile: Dockerfile
    image: ${IMAGE_TAG:-vpn-controls}:${IMAGE_VERSION:-1.2}
    restart: unless-stopped
    env_file:
      - "${APP_ENV_FILE:-./app.env}"
    volumes:
      - type: bind
        source: "${APP_DATA_DIR:-./data}"
        target: /data
      - "/run/strongswan:/run/strongswan:ro"
      - "/etc/strongswan:/etc/strongswan:ro"
      - "/etc/strongswan/users:/etc/strongswan/users"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
        compress: "true"
