from abc import ABC
from typing import Optional


class Controls(ABC):
    def add_user(self, user_id: int, username: str, password: str) -> int: ...

    def remove_all(self, user_id: int): ...

    def remove_user(self, user_id: int, position: int) -> Optional[int]: ...

    def set_password(self, user_id: int, position: int, password: str) -> Optional[int]: ...

    def set_username(self, user_id: int, position: int, username: str) -> Optional[int]: ...

    def get_account(self, user_id: int, position: int) -> Optional[tuple[str, str]]: ...

    def get_accounts(self, user_id: int, *positions: int) -> list[tuple[str, str]]: ...

    def update_hook(self): ...
