name: Deployment

on:
  pull_request:
    branches: [ master ]
    types: [ closed ]

jobs:
  deploy:
    if: github.event.pull_request.merged == true
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3
      with:
        ref: ${{ github.event.pull_request.head.sha }}
    - name: Stop existing containers
      run: docker compose down
    - name: Build and start containers
      env:
        APP_ENV_FILE: /etc/vpn-controls/app.env
        APP_DATA_DIR: /var/lib/vpn-controls
      run: docker compose up -d --build