name: Deployment

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3
    - name: Stop existing containers
      run: docker compose down
    - name: Build and start containers
      env:
        APP_ENV_FILE: /etc/vpn-controls/app.env
        APP_DATA_DIR: /var/lib/vpn-controls
      run: docker compose up -d --build