name: Upload Python Package

on:
  push:
    branches: [ testo ]
  pull_request:
    branches: [ master ]

jobs:
  deploy:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3
    - name: task1
      run: touch 12345
